l_english:
 DISPLAYNAME: "Europa Universalis IV To Victoria II"
 SOURCEGAME: "Europa Universalis IV"
 TARGETGAME: "Victoria II"
 FOLDER1: "Europa Universalis IV install directory"
 FOLDER1TIP: "A path on your computer where Europa Universalis IV is installed"
 FOLDER2: "EU4 Documents Directory"
 FOLDER2TIP: "A path on your computer where Europa Universalis IV keeps temporary files"
 FOLDER3: "CK2 Export Directory"
 FOLDER3TIP: "A path on your computer where Crusader Kings II keeps exported games"
 FOLDER4: "EU4 Steam Workshop Directory"
 FOLDER4TIP: "A path on your computer where Steam workshop keeps EU4 mods"
 FOLDER5: "Victoria II directory"
 FOLDER5TIP: "A path on your computer where Victoria II is installed"
 FOLDER6: "Victoria II documents directory"
 FOLDER6TIP: "A path on your computer where Victoria II keeps temporary files"
 FOLDER7: "Victoria II mod directory"
 FOLDER7TIP: "A path on your computer where Victoria II mods are located"
 FILE1: "Path to the converter executable"
 FILE1TIP: "Path to EU4ToVic2Converter.exe"
 FILE2: "Path to the EU4 Savegame"
 FILE2TIP: "Path to your savegame from EU4"
