l_russian:
 CK2DISPLAYNAME: "из Crusader Kings II в Европу Универсалис IV"
 EU4DISPLAYNAME: "из Европы Универсалис IV в Викторию II"
 VIC2DISPLAYNAME: "из Виктории II в Hearts of Iron IV"
 CK2GAME: "Crusader Kings II"
 EU4GAME: "Европа Универсалис IV"
 VIC2GAME: "Виктория II"
 HOI4GAME: "Hearts of Iron IV"
 CK2FOLDER: "Crusader Kings II Установить каталог"
 CK2FOLDERTIP: "Путь на вашем компьютере, где установлен Crusader Kings II"
 CK2MOD: "Crusader Kings II Мод Каталог"
 CK2MODTIP: "Путь на вашем компьютере, где хранятся моды Crusader Kings II"
 EU4FOLDER: "Европа Универсалис IV Установить каталог"
 EU4FOLDERTIP: "Путь на вашем компьютере, где установлена Европа Универсалис IV"
 EU4MOD: "Европа Универсалис IV Steam Мастерская Мод Каталог"
 EU4MODTIP: "Путь на вашем компьютере, где Европа Универсалис IV хранит Steam моды"
 VIC2FOLDER: "Установочный каталог Виктория II"
 VIC2FOLDERTIP: "Путь на вашем компьютере, где установлена Виктория II"
 VIC2MOD: "Виктория II Мод Каталог"
 VIC2MODTIP: "Путь на вашем компьютере, где хранятся моды Виктория II"
 HOI4FOLDER: "Установочный каталог Hearts of Iron IV"
 HOI4FOLDERTIP: "Путь на вашем компьютере, где установлен Hearts of Iron IV"
 HOI4MOD: "Модный каталог Hearts of Iron IV"
 HOI4MODTIP: "Путь на вашем компьютере, где хранятся моды от Hearts of Iron IV"
 CK2FILE: "Путь к исполняемому файлу конвертера"
 CK2FILETIP: "Путь к CK2ToEU4Converter.exe"
 CK2SAVE: "Путь к сохранению игры CK2"
 CK2SAVETIP: "Путь к вашей сохраненной игре от CK2"
 EU4FILE: "Путь к исполняемому файлу конвертера"
 EU4FILETIP: "Путь к EU4ToVic2Converter.exe"
 EU4SAVE: "Путь к сохранению игры EU4"
 EU4SAVETIP: "Путь к вашей сохраненной игре из EU4"
 VIC2FILE: "Путь к исполняемому файлу конвертера"
 VIC2FILETIP: "Путь к Vic2ToHoI4Converter.exe"
 VIC2SAVE: "Путь к сохранению игры Vic2"
 VIC2SAVETIP: "Путь к вашей сохраненной игре от Vic2"
 EU4DOC: "Справочник документов Европа Универсалис IV"
 EU4DOCTIP: "Путь на вашем компьютере, где Европа Универсалис IV хранит временные файлы"
 CK2EXP: "Crusader Kings II Экспортный каталог"
 CK2EXPTIP: "(Необязательно) Путь на вашем компьютере, где Crusader Kings II хранит экспортированные игры"
 VIC2DOC: "Каталог документов Виктории II"
 VIC2DOCTIP: "Путь на вашем компьютере, где Виктория II хранит временные файлы"