l_latin:
 CK2DISPLAYNAME: "ex Crusader Kings II ad Europam Universalem IV"
 EU4DISPLAYNAME: "ex Europa Universali ad Victoriam II"
 VIC2DISPLAYNAME: "ex Victoria II ad Hearts of Iron IV"
 CK2GAME: "Crusader Kings II"
 EU4GAME: "Europa Universalis IV"
 VIC2GAME: "Victoria II"
 HOI4GAME: "Hearts of Iron IV"
 CK2FOLDER: "Scapus locationis Crusader Kings II"
 CK2FOLDERTIP: "Via in qua locatus est ludus Crusader Kings II"
 CK2MOD: "Scapus correctionum Crusader Kings II"
 CK2MODTIP: "Via in qua locatae sunt correctiones Crusader Kings II"
 EU4FOLDER: "Scapus locationis Europae Universalis IV"
 EU4FOLDERTIP: "Via in qua locatus est ludus Europa Universalis IV"
 EU4MOD: "Scapus correctionum Steam Workshop Europae Universalis IV"
 EU4MODTIP: "Via in qua locatae sunt Steam correctiones Europae Universalis IV"
 VIC2FOLDER: "Scapus locationis Victoriae II"
 VIC2FOLDERTIP: "Via in qua locatus est ludus Victoria II"
 VIC2MOD: "Scapus correctionum Victoriae II"
 VIC2MODTIP: "Via in qua locatae sunt correctiones Victoriae II"
 HOI4FOLDER: "Scapus locationis Hearts of Iron IV"
 HOI4FOLDERTIP: "Via in qua locatus est ludus Hearts of Iron IV"
 HOI4MOD: "Scapus correctionum Hearts of Iron IV"
 HOI4MODTIP: "Via in qua locatae sunt correctiones Hearts of Iron IV"
 CK2FILE: "Via programmatis"
 CK2FILETIP: "Via ad CK2ToEU4Converter.exe"
 CK2SAVE: "Via ad conditum CK2"
 CK2SAVETIP: "Via ad conditum CK2"
 EU4FILE: "Via programmatis"
 EU4FILETIP: "Via ad EU4ToVic2Converter.exe"
 EU4SAVE: "Via ad conditum EU4"
 EU4SAVETIP: "Via ad conditum EU4"
 VIC2FILE: "Via programmatis"
 VIC2FILETIP: "Via ad Vic2ToHoI4Converter.exe"
 VIC2SAVE: "Via ad conditum Vic2"
 VIC2SAVETIP: "Via ad conditum Vic2"
 EU4DOC: "Scapus documentorum Europae Universalis IV"
 EU4DOCTIP: "Via in qua Europa Universalis IV scribit fasciculos temporales"
 CK2EXP: "Scapus iactorum Crusader Kings II"
 CK2EXPTIP: "(Facultativus) Via in qua Crusader Kings II iacit ludos conditos"
 VIC2DOC: "Scapus documentorum Victoriae II"
 VIC2DOCTIP: "Via in qua Victoria II scribit fasciculos temporales"