l_french:
 DISPLAYNAME: "Europe Universalis IV à Victoria II"
 SOURCEGAME: "Europa Universalis IV"
 TARGETGAME: "Victoria II"
 FOLDER1: "Répertoire d'installation d'Europa Universalis IV"
 FOLDER1TIP: "Un chemin sur votre ordinateur où Europa Universalis IV est installé"
 FOLDER2: "Répertoire des documents EU4"
 FOLDER2TIP: "Un chemin sur votre ordinateur où Europa Universalis IV conserve des fichiers temporaires"
 FOLDER3: "Répertoire d'exportation CK2"
 FOLDER3TIP: "Un chemin sur votre ordinateur où Crusader Kings II conserve les jeux exportés"
 FOLDER4: "Annuaire des ateliers EU4 Steam"
 FOLDER4TIP: "Un chemin sur votre ordinateur où l'atelier Steam conserve les mods EU4"
 FOLDER5: "Annuaire Victoria II"
 FOLDER5TIP: "Un chemin sur votre ordinateur où Victoria II est installé"
 FOLDER6: "Répertoire des documents Victoria II"
 FOLDER6TIP: "Un chemin sur votre ordinateur où Victoria II conserve des fichiers temporaires"
 FOLDER7: "Répertoire des mods Victoria II"
 FOLDER7TIP: "Un chemin sur votre ordinateur où se trouvent les mods Victoria II"
 FILE1: "Chemin vers l'exécutable du convertisseur"
 FILE1TIP: "Chemin vers EU4ToVic2Converter.exe"
 FILE2: "Chemin vers le jeu de sauvegarde EU4"
 FILE2TIP: "Chemin vers votre sauvegarde depuis EU4"
