l_italian:
 CK2DISPLAYNAME: "da Crusader Kings II a Europa Universalis IV"
 EU4DISPLAYNAME: "da Europa Universalis IV a Victoria II"
 VIC2DISPLAYNAME: "da Victoria II a Hearts of Iron IV"
 CK2GAME: "Crusader Kings II"
 EU4GAME: "Europa Universalis IV"
 VIC2GAME: "Victoria II"
 HOI4GAME: "Hearts of Iron IV"
 CK2FOLDER: "Cartella di installazione di Crusader Kings II"
 CK2FOLDERTIP: "Il percorso in cui è installato Crusader Kings II"
 CK2MOD: "Cartella delle mod per Crusader Kings II"
 CK2MODTIP: "Il percorso in cui Crusader Kings II memorizza le mod"
 EU4FOLDER: "Cartella di installazione di Europa Universalis IV"
 EU4FOLDERTIP: "Il percorso in cui è installato Europa Universalis IV"
 EU4MOD: "Cartella delle Steam Workshop mod per Europa Universalis IV"
 EU4MODTIP: "Il percorso in cui Europa Universalis IV memorizza le Steam mod"
 VIC2FOLDER: "Cartella di installazione di Victoria II"
 VIC2FOLDERTIP: "Il percorso in cui è installato Victoria II"
 VIC2MOD: "Cartella delle mod per Victoria II"
 VIC2MODTIP: "Il percorso in cui Victoria II memorizza le mod"
 HOI4FOLDER: "Cartella di installazione di Hearts of Iron IV"
 HOI4FOLDERTIP: "Il percorso in cui è installato Hearts of Iron IV"
 HOI4MOD: "Cartella delle mod per Hearts of Iron IV"
 HOI4MODTIP: "Il percorso in cui Hearts of Iron IV memorizza le mod"
 CK2FILE: "Percorso dell'eseguibile del convertitore"
 CK2FILETIP: "Percorso di CK2ToEU4Converter.exe"
 CK2SAVE: "Percorso del savegame CK2"
 CK2SAVETIP: "Percorso per il tuo savegame da CK2"
 EU4FILE: "Percorso dell'eseguibile del convertitore"
 EU4FILETIP: "Percorso di EU4ToVic2Converter.exe"
 EU4SAVE: "Percorso per il savegame EU4"
 EU4SAVETIP: "Percorso per il tuo savegame da EU4"
 VIC2FILE: "Percorso dell'eseguibile del convertitore"
 VIC2FILETIP: "Percorso di Vic2ToHoI4Converter.exe"
 VIC2SAVE: "Percorso per il savegame Vic2"
 VIC2SAVETIP: "Percorso per il tuo savegame da Vic2"
 EU4DOC: "Cartella dei documenti di Europa Universalis IV"
 EU4DOCTIP: "Un percorso in cui Europa Universalis IV conserva file temporanei"
 CK2EXP: "Cartella di esportazione di Crusader Kings II"
 CK2EXPTIP: "(Opzionale) Un percorso in cui Crusader Kings II mantiene i giochi esportati"
 VIC2DOC: "Cartella dei documenti di Victoria II"
 VIC2DOCTIP: "Un percorso in cui Victoria II conserva i file temporanei"