l_french:
 CK2DISPLAYNAME: "de Crusader Kings II à Europa Universalis IV"
 EU4DISPLAYNAME: "d'Europa Universalis IV à Victoria II"
 VIC2DISPLAYNAME: "de Victoria II à Hearts of Iron IV"
 CK2GAME: "Crusader Kings II"
 EU4GAME: "Europa Universalis IV"
 VIC2GAME: "Victoria II"
 HOI4GAME: "Hearts of Iron IV"
 CK2FOLDER: "Répertoire d'installation de Crusader Kings II"
 CK2FOLDERTIP: "Le chemin sur votre ordinateur où Crusader Kings II est installé"
 CK2MOD: "Répertoire des mods Crusader Kings II"
 CK2MODTIP: "Le chemin sur votre ordinateur où Crusader Kings II stocke les mods"
 EU4FOLDER: "Répertoire d'installation d'Europa Universalis IV"
 EU4FOLDERTIP: "Le chemin sur votre ordinateur où Europa Universalis IV est installé"
 EU4MOD: "Répertoire des Steam Workshop mods Europa Universalis IV"
 EU4MODTIP: "Le chemin sur votre ordinateur où Europa Universalis IV stocke les Steam mods"
 VIC2FOLDER: "Répertoire d'installation de Victoria II"
 VIC2FOLDERTIP: "Le chemin sur votre ordinateur où Victoria II est installé"
 VIC2MOD: "Répertoire des mods Victoria II"
 VIC2MODTIP: "Le chemin sur votre ordinateur où Victoria II stocke les mods"
 HOI4FOLDER: "Répertoire d'installation de Hearts of Iron IV"
 HOI4FOLDERTIP: "Le chemin sur votre ordinateur où Hearts of Iron IV est installé"
 HOI4MOD: "Répertoire des mods Hearts of Iron IV"
 HOI4MODTIP: "Le chemin sur votre ordinateur où Hearts of Iron IV stocke les mods"
 CK2FILE: "Chemin vers l'exécutable du convertisseur"
 CK2FILETIP: "Chemin vers CK2ToEU4Converter.exe"
 CK2SAVE: "Chemin vers la sauvegarde CK2"
 CK2SAVETIP: "Chemin vers votre sauvegarde de CK2"
 EU4FILE: "Chemin vers l'exécutable du convertisseur"
 EU4FILETIP: "Chemin vers EU4ToVic2Converter.exe"
 EU4SAVE: "Chemin vers la sauvegarde de EU4"
 EU4SAVETIP: "Chemin vers votre sauvegarde depuis EU4"
 VIC2FILE: "Chemin vers l'exécutable du convertisseur"
 VIC2FILETIP: "Chemin d'accès à Vic2ToHoI4Converter.exe"
 VIC2SAVE: "Chemin vers la sauvegarde Vic2"
 VIC2SAVETIP: "Chemin vers votre sauvegarde de Vic2"
 EU4DOC: "Répertoire des documents Europa Universalis IV"
 EU4DOCTIP: "Un chemin sur votre ordinateur où Europa Universalis IV conserve des fichiers temporaires"
 CK2EXP: "(Facultatif) Répertoire d'exportation de Crusader Kings II"
 CK2EXPTIP: "(Facultatif) Un chemin sur votre ordinateur où Crusader Kings II conserve les jeux exportés"
 VIC2DOC: "Répertoire des documents Victoria II"
 VIC2DOCTIP: "Un chemin sur votre ordinateur où Victoria II conserve des fichiers temporaires"